### ISSUE TITLE
StaticInjectorError

### ISSUE THREAD

**Issue by alexsintoni** [ShinDarth/ngx-duration-picker#9] opened 2018-08-01 06:50 UTC
Hi,

I just tried this component in my project but when I try it I get the following error:

```
ERROR Error: StaticInjectorError(MystaffAppModule)[NgIf -> ViewContainerRef]: 
  StaticInjectorError(Platform: core)[NgIf -> ViewContainerRef]: 
    NullInjectorError: No provider for ViewContainerRef!
```

Apprently the error is here:

```
      <tr *ngIf="config.showLetters">     <<===== Error
        <td *ngIf="config.showNegative"></td>
        <td *ngIf="config.showYears">Y</td>
        <td *ngIf="config.showMonths">M</td>
        <td *ngIf="config.showWeeks">W</td>
        <td *ngIf="config.showDays">D</td>
        <td *ngIf="config.showHours">H</td>
        <td *ngIf="config.showMinutes">M</td>
        <td *ngIf="config.showSeconds">S</td>
      </tr>
```

**Comment by ShinDarth** [comment] 2018-08-03 08:03
hi, what version of Angular are you using? How to reproduce this issue? Please provide some minimal reproduction steps

**Comment by ShinDarth** [comment] 2018-08-06 09:27
@alexsintoni any news with this?

**Comment by alexsintoni** [comment] 2018-08-21 09:17
@ShinDarth 
I apologise for my late reply but I was on holiday. Anyway, I didn't check it again after that error.
Please find below my answers:

- version of Angular:
     "@angular/animations": "6.0.3",
    "@angular/common": "6.0.3",
    "@angular/compiler": "6.0.3",
    "@angular/core": "6.0.3",
    "@angular/forms": "6.0.3",
    "@angular/http": "6.0.3",
    "@angular/platform-browser": "6.0.3",
    "@angular/platform-browser-dynamic": "6.0.3",

- How to reproduce this issue:
well, I just followed the instruction in [README.md](https://github.com/ShinDarth/ngx-duration-picker) 

1. npm install --save ngx-duration-picker
2. Then in your app.module.ts add DurationPickerModule between your imports
3. <app-duration-picker [(value)]="myDuration"></app-duration-picker>

But when I launched the app and accessed the page containing the ```app-duration-picker``` component, I got the error.

**Comment by ShinDarth** [comment] 2018-08-21 09:55
@alexsintoni what version of `ngx-duration-picker` are you using?

**Comment by alexsintoni** [comment] 2018-08-21 13:03
Hi @ShinDarth, 
at the moment I don't remember because I removed it after that error (sure it was last version available when I created this issue). 
I can try to add it again and I will let you know if I will have again the error.

**Comment by ShinDarth** [comment] 2018-08-21 14:02
@alexsintoni please try again using the latest Angular and ngx-duration-picker versions. I will also try it on a fresh angular app.

**Comment by ShinDarth** [comment] 2018-08-21 14:46
@alexsintoni I've just created a new Angular app (generated with Angular CLI version `1.6.4`) which uses Angular `1.6.3` and ngx-duration-picker `1.4.1`:

https://github.com/ShinDarth/angular-test-ngx-duration-picker

it looks working fine, I cannot reproduce your error. Maybe it's something wrong with your codebase?

**Comment by ShinDarth** [comment] 2018-09-02 12:47
closing this, feel free to reopen the issue if you think it's still valid

**Closed by ShinDarth** 2018-09-02 12:47 UTC
